# Generated by Django 5.2.17 on 2026-09-26 08:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(help_text='Masalan: +998901234567', max_length=20, unique=True, verbose_name='Telefon raqam')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Familiya')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('passport_series', models.CharField(blank=True, max_length=10, null=True, verbose_name='Pasport seriyasi & raqami')),
                ('pinfl', models.CharField(blank=True, max_length=14, null=True, verbose_name='JSHSHIR (PINFL)')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Yashash manzili')),
                ('role', models.CharField(choices=[('CLIENT', 'Mijoz'), ('ADMIN', 'Administrator')], default='CLIENT', max_length=10, verbose_name='Roli')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('inactive', 'Faolsiz'), ('blocked', 'Bloklangan')], default='active', max_length=10, verbose_name='Status')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Xodim')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Ro'yxatdan o'tgan")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_front', models.ImageField(upload_to='kyc/passports/', verbose_name='Pasport old qismi')),
                ('passport_back', models.ImageField(upload_to='kyc/passports/', verbose_name='Pasport orqa qismi')),
                ('selfie_with_passport', models.ImageField(upload_to='kyc/selfies/', verbose_name='Pasport bilan selfie')),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('APPROVED', 'Tasdiqlandi'), ('REJECTED', 'Rad etildi')], default='PENDING', max_length=15, verbose_name='Hujjat holati')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Rad etish sababi')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name="Ko'rib chiqilgan vaqt")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'KYC Hujjat',
                'verbose_name_plural': 'KYC Hujjatlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
