services:
  - type: web
    name: meco-backend
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma db push
    startCommand: node server/index.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:./dev.db
      - key: FRONTEND_ORIGIN
        value: https://voltmaxhub.uz,https://www.voltmaxhub.uz,https://powerbank011.netlify.app
      - key: JWT_SECRET
        generateValue: true
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
