# Generated by Django 5.2.17 on 2026-09-26 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, default='box', max_length=50, verbose_name='Ikona')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Mahsulot nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Kunlik ijara narxi (UZS)')),
                ('deposit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Zalok summa (UZS)')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='Rasm havolasi (URL)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Mavjudmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
