# Generated by Django 5.2.17 on 2026-09-26 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Ijara boshlanish sanasi')),
                ('end_date', models.DateField(verbose_name='Ijara tugash sanasi')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Jami ijara summasi')),
                ('status', models.CharField(choices=[('PENDING_VERIFICATION', 'Hujjat kutilmoqda'), ('APPROVED', 'Tasdiqlangan'), ('ACTIVE', 'Faol ijara'), ('RETURNED', 'Qaytarilgan'), ('OVERDUE_LEGAL', "Sud jarayonida (Muddati o'tgan)")], default='PENDING_VERIFICATION', max_length=25, verbose_name='Buyurtma holati')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='legal_pdfs/', verbose_name='Sud Arizasi (PDF)')),
                ('overdue_days', models.PositiveIntegerField(default=0, verbose_name="Muddati o'tgan kunlar")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Buyurtma vaqti')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='products.product', verbose_name='Mahsulot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Mijoz')),
            ],
            options={
                'verbose_name': 'Ijara Buyurtmasi',
                'verbose_name_plural': 'Ijara Buyurtmalari',
                'ordering': ['-created_at'],
            },
        ),
    ]
